### ISSUE TITLE
Any example notebook to run Yolo or other object detection model on Kria PYNQ? 

### ISSUE THREAD

**Issue by krishnaadithya** [Xilinx/Kria-PYNQ#11]

**Comment by skalade** [comment]
Hi there,

Kria-PYNQ comes with examples from [DPU-PYNQ](https://github.com/Xilinx/DPU-PYNQ), there are image classification (resnet50) examples, but currently no object detection. 

If you are looking for info/help I would recommend writing a post on the [pynq support forum](https://discuss.pynq.io/).

Going to close this issue as it's not really Kria-PYNQ issue.
