### ISSUE TITLE
README needs updates for git submodules 

### ISSUE THREAD

**Issue by nimish** [Xilinx/Kria-PYNQ#12]
`git submodule update --recursive --init`

Is required before running `install.sh` otherwise the script will fail with a `pushd` error.

**Comment by mariodruiz** [comment]
Hi @nimish,

The `install.sh` script clones the submodules here https://github.com/Xilinx/Kria-PYNQ/blob/main/install.sh#L29-L35 
So, cloning recursively this repo should be not necessary

**Comment by nimish** [comment]
> Hi @nimish,
> 
> 
> 
> The `install.sh` script clones the submodules here https://github.com/Xilinx/Kria-PYNQ/blob/main/install.sh#L29-L35 
> 
> So, cloning recursively this repo should be not necessary
> 
> 
> 
> 

Just tried this; it doesn't appear to clone correctly without explicitly enabling submodules on a freshly imaged KV260 🤷‍♂️

**Comment by mariodruiz** [comment]
would you like to PR with the change to the README?

**Comment by nimish** [comment]
Yep

**Comment by mariodruiz** [comment]
Would you mind cloning the repo again (without `--recursive`) and then run `git submodule init && git submodule update` and report if the submodules are cloned?

**Comment by nimish** [comment]
Only the `pynq` one is (one level). The submodules of `pynq` aren't.

Submodules are an enormous PITA, best to not use them IMO

**Comment by nimish** [comment]
Only the `pynq` one is (one level). The submodules of `pynq` aren't.

Submodules are an enormous PITA, best to not use them IMO

`git submodule update --init --recursive` is what worked however

**Comment by STFleming** [comment]
Closing for now -- see comments on relevant PR (https://github.com/Xilinx/Kria-PYNQ/pull/13) can reopen if it is still a problem for people.
