### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by Nunigan** [Xilinx/Kria-PYNQ#14]
Hi Guys

I have KV260 AI Vision Starter Kit.
Boot binary:2021.2_update2_BOOT.BIN
Ubuntu Desktop 20.04.3 LTS

 I get following error after `sudo bash install.sh`

_Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:_

_The following packages have unmet dependencies:
libopencv-viz4.2 : Depends: libvtk6.3 (>= 6.3.0+dfsg2) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages._

can someone help me?

Best regards Michael

**Comment by skalade** [comment]
Hi Michael,

I just tried this on a fresh image and looks like this happens at the [very end](https://github.com/Xilinx/Kria-PYNQ/blob/main/install.sh#L193) of the install script doing some cleanup (pynq and all overlays have already been installed). We'll investigate what to do about the error, but in the meantime you should be able to login to jupyter and run all the examples without problem.

Thanks
Shawn

**Comment by patrickgeel** [comment]
Hi Michael,

I was struggling with this issue as well, and was not able to run any of the notebooks. I started off with a clean image and built the following commit (43e33853dccb8ec6ae83efe3c6b73e1c8359747c) and the issue was solved for me. I am now able to run the notebooks. I believe that #15 is the same as this commit but not 100% certain. 

Kind regards,
Patrick

**Comment by fpgadeveloper** [comment]
Just to say that I also had the same issue and it went away by installing from the commit specified by Patrick above. Thanks Patrick!
