### ISSUE TITLE
install.sh: line 39: systemctl: command not found install pynq on kv260 petalinux prebuild

### ISSUE THREAD

**Issue by chenguoping76** [Xilinx/Kria-PYNQ#18]
![Y%QQ(NG%ZH08M`3YJI(_((G](https://user-images.githubusercontent.com/35511222/183241553-0832c96c-e827-4d8e-8595-049ac34e212f.png)

**Comment by mariodruiz** [comment]
Hi @chenguoping76,

The PYNQ installation is verified only in the certified Ubuntu image, and it would appear that you are using a Petalinux image.
I suggest you download the certified Ubuntu image.

Mario
