### ISSUE TITLE
support to mipi sensor in the kria accessory kit

### ISSUE THREAD

**Issue by DavideConficconi** [Xilinx/Kria-PYNQ#22]
Hello,

It seems that for now PYNQ just support the MIPI sensor from digilent pcam5 and not the one included in the basic accessory pack of the KV260 https://www.xilinx.com/products/som/kria/kv260-vision-starter-kit/basic-accessory-pack.html.
Is there any way to add support to it even with the base overlay?
or it is a completely different hardware design?
Any chance to just implement a new python driver?

Thanks for the help whatever the answer
Best

Davide

**Comment by mariodruiz** [comment]
Hi @DavideConficconi,

The base overlay does not have hardware support for the IR1335 camera. 

Mario
