### ISSUE TITLE
More emphasis on device firmware version in Getting start guide

### ISSUE THREAD

**Issue by JieGH** [Xilinx/Kria-PYNQ#29]
Hi

The wiki pointed out the firmware version of KV260 should match with Ubuntu version. 
For example the FW 2021.1 will not boot Ubuntu 22. 
This is NOT reflected on the getting to start guide in Xilinx website though it did cover in wiki 

https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/1641152513#Ubuntu-LTS

I just received a device manufactured in July 2022. But I unable to boot Ubuntu 22. 
I later realised the FW need to be updated. 

I recommend put more emphasis on the FW version checking step in getting start guide. 

Thanks

**Comment by mariodruiz** [comment]
Hi @JieGH,

This is well cover in different places, for instance in the Ubuntu download page https://ubuntu.com/download/amd-xilinx

Fell free to PR if you would like this to be included in the README.

Mario
