### ISSUE TITLE
Did Kria-PYNQ support pynq.PMBus?

### ISSUE THREAD

**Issue by lrzniu** [Xilinx/Kria-PYNQ#32]
I build Kria-PYNQ in KV260. Following the link 'https://pynq.readthedocs.io/en/latest/pynq_libraries/pmbus.html?highlight=rails#example',  
I could not see the conf of sensors in '/etc/sensors.d' .  I'm not sure it is my problem...

**Comment by schelleg** [comment]
hi @lrzniu - we didn't populate the sensorconf for the KV260. If someone wants to look into what's possible, it'd be a great contribution ...
