### ISSUE TITLE
logictools overlay support yet?

### ISSUE THREAD

**Issue by JieGH** [Xilinx/Kria-PYNQ#33]
Hi,  

I am trying to load logictools overlay.
I encountered some error.
```bash
No module named 'pynq.overlays.logictools'
```

Did the logictools overlay support the KV260 yet?
Are the supported overlay only include in readme https://github.com/Xilinx/Kria-PYNQ#included-overlays

Kind regards
Jie

**Comment by schelleg** [comment]
Hi @JieGH - there are no plans to port that overlay to the KV260.
