### ISSUE TITLE
Kria KV260 sudo bash install.sh -b KV260

### ISSUE THREAD

**Issue by thitathita** [Xilinx/Kria-PYNQ#35]
Hi everyone,
I am new beginner for Linux OS and Xilinx FPGA, inculde Kria KV260.
I have been following this tutorial, https://www.fpgadeveloper.com/setup-pynq-on-the-kria-kv260-vision-ai-starter-kit/. In order to learn how this Kria working.
Now I am facing the problem while clone from Github, **sudo bash install.sh -b KV260**
The terminal shows:
![image](https://user-images.githubusercontent.com/122670685/212465760-227a55ee-7190-4748-9756-88e4156e1bda.png)
I also checked the version that is installed, it is
apt-cache policy python3.10-venv: 
python3.10-venv:
  Installed: 3.10.6-1~22.04.2
  Candidate: 3.10.6-1~22.04.2
  Version table:
 *** 3.10.6-1~22.04.2 500
        500 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages
        500 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages
        100 /var/lib/dpkg/status
     3.10.4-3 500
        500 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages

How can I successfully clone from this github?
best regards,
thitathita

**Comment by skalade** [comment]
Hi @thitathita,

Could you share your exact steps of reproducing the issue?

I just tried the install on my KV260 with a fresh image and it went fine. Here are the steps:
1. Download and burn 22.04 Ubuntu image from https://ubuntu.com/download/amd-xilinx
2. Boot board and connect via serial connection
3. 
```
git clone https://github.com/xilinx/kria-pynq
cd kria-pynq/
sudo bash install.sh -b KV260
```

Thanks
Shawn

**Comment by thitathita** [comment]
> Hi @thitathita,
> 
> Could you share your exact steps of reproducing the issue?
> 
> I just tried the install on my KV260 with a fresh image and it went fine. Here are the steps:
> 
>     1. Download and burn 22.04 Ubuntu image from https://ubuntu.com/download/amd-xilinx
> 
>     2. Boot board and connect via serial connection
> 
> 
> ```
> git clone https://github.com/xilinx/kria-pynq
> cd kria-pynq/
> sudo bash install.sh -b KV260
> ```
> 
> Thanks Shawn

Hello!
I just successfully installed PYNQ regarding downgrade Ubuntu to version 20.04. That works fine!

**Comment by skalade** [comment]
Will close this out then, thanks for reporting back that the install worked. Feel free to re-open the issue if there's still a problem.

Thanks
Shawn
