### ISSUE TITLE
install.sh fails with ‘/home/root/jupyter_notebooks/’ not found

### ISSUE THREAD

**Issue by jue-s** [Xilinx/Kria-PYNQ#41]
when following instructions to install pynq, when running "sudo bash install.sh KD240", it fails with the following:
“cp: cannot create directory ‘/home/root/jupyter_notebooks/’:  no such file or directory”

can workaround with manually creating that directory before running install.sh, but thats not part of the instructions right now.

**Comment by skalade** [comment]
Hi @jue-s, I made a PR for this here https://github.com/Xilinx/Kria-PYNQ/pull/42, could you let me know if the copy path change  fixes the issue for you? Thanks!
