### ISSUE TITLE
build the PYNQ framework based on kria kv260.

### ISSUE THREAD

**Issue by ctgulzh** [Xilinx/Kria-PYNQ#46]
I want to build the PYNQ framework based on kria kv260. When running the command: sudo bash install.sh -b KV260, the following error occurs: could not find a version that satisfies the requirement numpy==1.26.4
I set the HTTP protocol to 1.1 and the cache postBuffer to 4G, but the problem still cannot be solved. Why does the above problem occur? Is it because of unstable network? The output information of shell operation is as follows:
![屏幕截图 2024-08-25 213446](https://github.com/user-attachments/assets/a075b3d8-5b77-4c9b-bb5a-da5344c0dbdd)

**Comment by mariodruiz** [comment]
Hi @ctgulzh,

You can try to relax this requirement. In your local copy of this repo, update this line

https://github.com/Xilinx/Kria-PYNQ/blob/21bf5e18a6dba20babe99108ac697d2cdc49645f/install.sh#L149

to

```sh
python3 -m pip install "numpy<2"
```

And try to reinstall

**Comment by ctgulzh** [comment]
ok,thank you,the problem has been solved！

**Comment by schelleg** [comment]
closing - problem resolved
