### ISSUE TITLE
DNU xmodel not working for Pytorch and Tensorflow

### ISSUE THREAD

**Issue by jnbli** [Xilinx/Kria-PYNQ#5]
Loading Pytorch and Tensorflow xmodels from Model Zoo don't work. Only loading caffe xmodels seem to work.

I am using Kria KV260 board. The example is from Kria-PYNQ and the notebook is dpu_resnet50.ipynb.

**Comment by skalade** [comment]
Duplicate issue here https://github.com/Xilinx/DPU-PYNQ/issues/77, closing this one.
